export interface Formula {
  id: string;
  name: string;
  formula: string;
  description?: string;
}

export interface FormulaCategory {
  id: string;
  title: string;
  icon: string;
  formulas: Formula[];
}

export const formulaCategories: FormulaCategory[] = [
  {
    id: "algebra",
    title: "Algebra",
    icon: "Variable",
    formulas: [
      { id: "a1", name: "Kvadrat tenglama", formula: "x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}", description: "ax² + bx + c = 0 tenglamaning yechimlari" },
      { id: "a2", name: "Vieta formulasi", formula: "x_1 + x_2 = -\\frac{b}{a}, \\quad x_1 \\cdot x_2 = \\frac{c}{a}" },
      { id: "a3", name: "Qisqa ko'paytirish", formula: "(a + b)^2 = a^2 + 2ab + b^2" },
      { id: "a4", name: "Qisqa ko'paytirish", formula: "(a - b)^2 = a^2 - 2ab + b^2" },
      { id: "a5", name: "Kvadratlar ayirmasi", formula: "a^2 - b^2 = (a - b)(a + b)" },
      { id: "a6", name: "Kublar yig'indisi", formula: "a^3 + b^3 = (a + b)(a^2 - ab + b^2)" },
      { id: "a7", name: "Kublar ayirmasi", formula: "a^3 - b^3 = (a - b)(a^2 + ab + b^2)" },
      { id: "a8", name: "Binom formulasi", formula: "(a + b)^n = \\sum_{k=0}^{n} C_n^k a^{n-k} b^k" },
      { id: "a9", name: "Kub yig'indisi", formula: "(a + b)^3 = a^3 + 3a^2b + 3ab^2 + b^3" },
      { id: "a10", name: "Kub ayirmasi", formula: "(a - b)^3 = a^3 - 3a^2b + 3ab^2 - b^3" },
      { id: "a11", name: "To'rtinchi daraja", formula: "(a + b)^4 = a^4 + 4a^3b + 6a^2b^2 + 4ab^3 + b^4" },
      { id: "a12", name: "Ildizlar yig'indisi", formula: "x_1^2 + x_2^2 = (x_1 + x_2)^2 - 2x_1x_2" },
      { id: "a13", name: "Ildizlar kublari", formula: "x_1^3 + x_2^3 = (x_1 + x_2)^3 - 3x_1x_2(x_1 + x_2)" },
      { id: "a14", name: "Diskriminant", formula: "D = b^2 - 4ac" },
      { id: "a15", name: "Logarifm asosiy", formula: "\\log_a b = \\frac{\\ln b}{\\ln a}" },
      { id: "a16", name: "Logarifm ko'paytma", formula: "\\log_a(xy) = \\log_a x + \\log_a y" },
      { id: "a17", name: "Logarifm bo'linma", formula: "\\log_a\\frac{x}{y} = \\log_a x - \\log_a y" },
      { id: "a18", name: "Logarifm daraja", formula: "\\log_a x^n = n \\log_a x" },
      { id: "a19", name: "Asos almashtirish", formula: "\\log_a b \\cdot \\log_b c = \\log_a c" },
      { id: "a20", name: "Eksponensial tenglama", formula: "a^x = b \\Rightarrow x = \\log_a b" },
    ]
  },
  {
    id: "geometry",
    title: "Geometriya",
    icon: "Triangle",
    formulas: [
      { id: "g1", name: "Uchburchak yuzi", formula: "S = \\frac{1}{2} \\cdot a \\cdot h", description: "a - asos, h - balandlik" },
      { id: "g2", name: "Pifagor teoremasi", formula: "c^2 = a^2 + b^2", description: "To'g'ri burchakli uchburchak" },
      { id: "g3", name: "Geron formulasi", formula: "S = \\sqrt{p(p-a)(p-b)(p-c)}", description: "p = (a+b+c)/2 - yarim perimetr" },
      { id: "g4", name: "Aylana uzunligi", formula: "C = 2\\pi r" },
      { id: "g5", name: "Doira yuzi", formula: "S = \\pi r^2" },
      { id: "g6", name: "Shar hajmi", formula: "V = \\frac{4}{3}\\pi r^3" },
      { id: "g7", name: "Shar sirti", formula: "S = 4\\pi r^2" },
      { id: "g8", name: "Silindr hajmi", formula: "V = \\pi r^2 h" },
      { id: "g9", name: "Konus hajmi", formula: "V = \\frac{1}{3}\\pi r^2 h" },
      { id: "g10", name: "To'rtburchak yuzi", formula: "S = a \\cdot b" },
      { id: "g11", name: "Parallelogramm yuzi", formula: "S = a \\cdot h" },
      { id: "g12", name: "Trapetsiya yuzi", formula: "S = \\frac{(a + b) \\cdot h}{2}" },
      { id: "g13", name: "Romb yuzi", formula: "S = \\frac{d_1 \\cdot d_2}{2}", description: "d₁, d₂ - diagonallar" },
      { id: "g14", name: "Muntazam ko'pburchak", formula: "S = \\frac{n \\cdot a^2}{4\\tan(\\pi/n)}" },
      { id: "g15", name: "Silindr sirti", formula: "S = 2\\pi r(r + h)" },
      { id: "g16", name: "Konus sirti", formula: "S = \\pi r(r + l)", description: "l - yasovchi" },
      { id: "g17", name: "Piramida hajmi", formula: "V = \\frac{1}{3}Sh", description: "S - asos yuzi" },
      { id: "g18", name: "Prizma hajmi", formula: "V = S \\cdot h" },
      { id: "g19", name: "Kesik konus", formula: "V = \\frac{\\pi h}{3}(R^2 + Rr + r^2)" },
      { id: "g20", name: "Ichki burchaklar", formula: "\\sum = (n-2) \\cdot 180°" },
      { id: "g21", name: "Mediana formulasi", formula: "m_a = \\frac{1}{2}\\sqrt{2b^2 + 2c^2 - a^2}" },
      { id: "g22", name: "Bissektrisa formulasi", formula: "l_a = \\frac{2bc \\cdot \\cos(A/2)}{b + c}" },
      { id: "g23", name: "Ichki aylana", formula: "r = \\frac{S}{p}", description: "S - yuz, p - yarim perimetr" },
      { id: "g24", name: "Tashqi aylana", formula: "R = \\frac{abc}{4S}" },
    ]
  },
  {
    id: "trigonometry",
    title: "Trigonometriya",
    icon: "Waves",
    formulas: [
      { id: "t1", name: "Asosiy ayniyat", formula: "\\sin^2 x + \\cos^2 x = 1" },
      { id: "t2", name: "Tangens", formula: "\\tan x = \\frac{\\sin x}{\\cos x}" },
      { id: "t3", name: "Kotangens", formula: "\\cot x = \\frac{\\cos x}{\\sin x}" },
      { id: "t4", name: "Qo'shish formulasi", formula: "\\sin(a + b) = \\sin a \\cos b + \\cos a \\sin b" },
      { id: "t5", name: "Qo'shish formulasi", formula: "\\cos(a + b) = \\cos a \\cos b - \\sin a \\sin b" },
      { id: "t6", name: "Ikkilangan burchak", formula: "\\sin 2x = 2 \\sin x \\cos x" },
      { id: "t7", name: "Ikkilangan burchak", formula: "\\cos 2x = \\cos^2 x - \\sin^2 x" },
      { id: "t8", name: "Sinuslar teoremasi", formula: "\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C} = 2R" },
      { id: "t9", name: "Kosinuslar teoremasi", formula: "c^2 = a^2 + b^2 - 2ab\\cos C" },
      { id: "t10", name: "Ayirish formulasi", formula: "\\sin(a - b) = \\sin a \\cos b - \\cos a \\sin b" },
      { id: "t11", name: "Ayirish formulasi", formula: "\\cos(a - b) = \\cos a \\cos b + \\sin a \\sin b" },
      { id: "t12", name: "Tangens qo'shish", formula: "\\tan(a + b) = \\frac{\\tan a + \\tan b}{1 - \\tan a \\tan b}" },
      { id: "t13", name: "Tangens ayirish", formula: "\\tan(a - b) = \\frac{\\tan a - \\tan b}{1 + \\tan a \\tan b}" },
      { id: "t14", name: "Uch karra burchak", formula: "\\sin 3x = 3\\sin x - 4\\sin^3 x" },
      { id: "t15", name: "Uch karra burchak", formula: "\\cos 3x = 4\\cos^3 x - 3\\cos x" },
      { id: "t16", name: "Yarim burchak", formula: "\\sin\\frac{x}{2} = \\pm\\sqrt{\\frac{1-\\cos x}{2}}" },
      { id: "t17", name: "Yarim burchak", formula: "\\cos\\frac{x}{2} = \\pm\\sqrt{\\frac{1+\\cos x}{2}}" },
      { id: "t18", name: "Ko'paytmaga aylantirish", formula: "\\sin a + \\sin b = 2\\sin\\frac{a+b}{2}\\cos\\frac{a-b}{2}" },
      { id: "t19", name: "Ko'paytmaga aylantirish", formula: "\\cos a + \\cos b = 2\\cos\\frac{a+b}{2}\\cos\\frac{a-b}{2}" },
      { id: "t20", name: "Ko'paytmaga aylantirish", formula: "\\sin a - \\sin b = 2\\cos\\frac{a+b}{2}\\sin\\frac{a-b}{2}" },
      { id: "t21", name: "Yig'indiga aylantirish", formula: "\\sin a \\cos b = \\frac{1}{2}[\\sin(a+b) + \\sin(a-b)]" },
      { id: "t22", name: "Sekans ayniyat", formula: "1 + \\tan^2 x = \\sec^2 x" },
      { id: "t23", name: "Kosekans ayniyat", formula: "1 + \\cot^2 x = \\csc^2 x" },
      { id: "t24", name: "Universal almashtirish", formula: "\\sin x = \\frac{2t}{1+t^2}, \\quad t = \\tan\\frac{x}{2}" },
    ]
  },
  {
    id: "calculus",
    title: "Matematik Analiz",
    icon: "TrendingUp",
    formulas: [
      { id: "c1", name: "Hosila ta'rifi", formula: "f'(x) = \\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}" },
      { id: "c2", name: "Daraja hosila", formula: "(x^n)' = nx^{n-1}" },
      { id: "c3", name: "Ko'paytma hosila", formula: "(uv)' = u'v + uv'" },
      { id: "c4", name: "Bo'linma hosila", formula: "\\left(\\frac{u}{v}\\right)' = \\frac{u'v - uv'}{v^2}" },
      { id: "c5", name: "Murakkab funksiya", formula: "(f(g(x)))' = f'(g(x)) \\cdot g'(x)" },
      { id: "c6", name: "Eksponenta hosila", formula: "(e^x)' = e^x" },
      { id: "c7", name: "Logarifm hosila", formula: "(\\ln x)' = \\frac{1}{x}" },
      { id: "c8", name: "Sinus hosila", formula: "(\\sin x)' = \\cos x" },
      { id: "c9", name: "Kosinus hosila", formula: "(\\cos x)' = -\\sin x" },
      { id: "c10", name: "Tangens hosila", formula: "(\\tan x)' = \\sec^2 x = \\frac{1}{\\cos^2 x}" },
      { id: "c11", name: "Kotangens hosila", formula: "(\\cot x)' = -\\csc^2 x = -\\frac{1}{\\sin^2 x}" },
      { id: "c12", name: "Arksinus hosila", formula: "(\\arcsin x)' = \\frac{1}{\\sqrt{1-x^2}}" },
      { id: "c13", name: "Arkkosinus hosila", formula: "(\\arccos x)' = -\\frac{1}{\\sqrt{1-x^2}}" },
      { id: "c14", name: "Arktangens hosila", formula: "(\\arctan x)' = \\frac{1}{1+x^2}" },
      { id: "c15", name: "Umumiy eksponenta", formula: "(a^x)' = a^x \\ln a" },
      { id: "c16", name: "Umumiy logarifm", formula: "(\\log_a x)' = \\frac{1}{x \\ln a}" },
      { id: "c17", name: "Lopital qoidasi", formula: "\\lim_{x \\to a}\\frac{f(x)}{g(x)} = \\lim_{x \\to a}\\frac{f'(x)}{g'(x)}" },
      { id: "c18", name: "Teylor qatori", formula: "f(x) = \\sum_{n=0}^{\\infty} \\frac{f^{(n)}(a)}{n!}(x-a)^n" },
      { id: "c19", name: "Makloren qatori", formula: "e^x = \\sum_{n=0}^{\\infty} \\frac{x^n}{n!}" },
      { id: "c20", name: "Sinus qatori", formula: "\\sin x = \\sum_{n=0}^{\\infty} \\frac{(-1)^n x^{2n+1}}{(2n+1)!}" },
    ]
  },
  {
    id: "integrals",
    title: "Integrallar",
    icon: "Sigma",
    formulas: [
      { id: "i1", name: "Daraja integrali", formula: "\\int x^n dx = \\frac{x^{n+1}}{n+1} + C, \\quad n \\neq -1" },
      { id: "i2", name: "Eksponenta integrali", formula: "\\int e^x dx = e^x + C" },
      { id: "i3", name: "Logarifm integrali", formula: "\\int \\frac{1}{x} dx = \\ln|x| + C" },
      { id: "i4", name: "Sinus integrali", formula: "\\int \\sin x dx = -\\cos x + C" },
      { id: "i5", name: "Kosinus integrali", formula: "\\int \\cos x dx = \\sin x + C" },
      { id: "i6", name: "Aniq integral", formula: "\\int_a^b f(x) dx = F(b) - F(a)" },
      { id: "i7", name: "Bo'laklab integrallash", formula: "\\int u dv = uv - \\int v du" },
      { id: "i8", name: "Tangens integrali", formula: "\\int \\tan x dx = -\\ln|\\cos x| + C" },
      { id: "i9", name: "Kotangens integrali", formula: "\\int \\cot x dx = \\ln|\\sin x| + C" },
      { id: "i10", name: "Sekans integrali", formula: "\\int \\sec x dx = \\ln|\\sec x + \\tan x| + C" },
      { id: "i11", name: "Arktangens integrali", formula: "\\int \\frac{dx}{1+x^2} = \\arctan x + C" },
      { id: "i12", name: "Arksinus integrali", formula: "\\int \\frac{dx}{\\sqrt{1-x^2}} = \\arcsin x + C" },
      { id: "i13", name: "Umumiy eksponenta", formula: "\\int a^x dx = \\frac{a^x}{\\ln a} + C" },
      { id: "i14", name: "Kvadrat ildiz", formula: "\\int \\frac{dx}{\\sqrt{a^2-x^2}} = \\arcsin\\frac{x}{a} + C" },
      { id: "i15", name: "Ratsional funksiya", formula: "\\int \\frac{dx}{x^2+a^2} = \\frac{1}{a}\\arctan\\frac{x}{a} + C" },
      { id: "i16", name: "Logarifmik integral", formula: "\\int \\ln x dx = x\\ln x - x + C" },
      { id: "i17", name: "Yoy uzunligi", formula: "L = \\int_a^b \\sqrt{1 + (f'(x))^2} dx" },
      { id: "i18", name: "Aylanish hajmi", formula: "V = \\pi \\int_a^b [f(x)]^2 dx" },
      { id: "i19", name: "Aylanish sirti", formula: "S = 2\\pi \\int_a^b f(x)\\sqrt{1+(f'(x))^2} dx" },
      { id: "i20", name: "Egri chiziq ostidagi yuz", formula: "S = \\int_a^b |f(x)| dx" },
    ]
  },
  {
    id: "probability",
    title: "Ehtimollik",
    icon: "Percent",
    formulas: [
      { id: "p1", name: "Klassik ehtimollik", formula: "P(A) = \\frac{m}{n}", description: "m - qulay hodisalar, n - barcha hodisalar" },
      { id: "p2", name: "Qo'shish qoidasi", formula: "P(A \\cup B) = P(A) + P(B) - P(A \\cap B)" },
      { id: "p3", name: "Ko'paytirish qoidasi", formula: "P(A \\cap B) = P(A) \\cdot P(B|A)" },
      { id: "p4", name: "Bernulli formulasi", formula: "P_n(k) = C_n^k p^k q^{n-k}" },
      { id: "p5", name: "Matematik kutilma", formula: "E(X) = \\sum_{i} x_i \\cdot P(x_i)" },
      { id: "p6", name: "Dispersiya", formula: "D(X) = E(X^2) - (E(X))^2" },
      { id: "p7", name: "O'rtacha kvadratik", formula: "\\sigma = \\sqrt{D(X)}" },
      { id: "p8", name: "Shartli ehtimollik", formula: "P(A|B) = \\frac{P(A \\cap B)}{P(B)}" },
      { id: "p9", name: "Bayes formulasi", formula: "P(A|B) = \\frac{P(B|A) \\cdot P(A)}{P(B)}" },
      { id: "p10", name: "To'liq ehtimollik", formula: "P(A) = \\sum_{i=1}^{n} P(H_i) \\cdot P(A|H_i)" },
      { id: "p11", name: "Normal taqsimot", formula: "f(x) = \\frac{1}{\\sigma\\sqrt{2\\pi}} e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}" },
      { id: "p12", name: "Puasson taqsimoti", formula: "P(k) = \\frac{\\lambda^k e^{-\\lambda}}{k!}" },
      { id: "p13", name: "Geometrik taqsimot", formula: "P(X=k) = (1-p)^{k-1} p" },
      { id: "p14", name: "Kovariatsiya", formula: "\\text{Cov}(X,Y) = E(XY) - E(X)E(Y)" },
      { id: "p15", name: "Korrelyatsiya", formula: "r = \\frac{\\text{Cov}(X,Y)}{\\sigma_X \\sigma_Y}" },
      { id: "p16", name: "Binomial kutilma", formula: "E(X) = np" },
      { id: "p17", name: "Binomial dispersiya", formula: "D(X) = npq" },
      { id: "p18", name: "Chebishev tengsizligi", formula: "P(|X - \\mu| \\geq k\\sigma) \\leq \\frac{1}{k^2}" },
    ]
  },
  {
    id: "combinatorics",
    title: "Kombinatorika",
    icon: "Grid3X3",
    formulas: [
      { id: "k1", name: "Faktorial", formula: "n! = 1 \\cdot 2 \\cdot 3 \\cdot ... \\cdot n" },
      { id: "k2", name: "O'rin almashtirish", formula: "P_n = n!" },
      { id: "k3", name: "Joylashtirish", formula: "A_n^k = \\frac{n!}{(n-k)!}" },
      { id: "k4", name: "Binom koeffitsient", formula: "C_n^k = \\frac{n!}{k!(n-k)!}" },
      { id: "k5", name: "Binom xossasi", formula: "C_n^k = C_n^{n-k}" },
      { id: "k6", name: "Paskal uchburchagi", formula: "C_n^k = C_{n-1}^{k-1} + C_{n-1}^k" },
      { id: "k7", name: "Takrorlanuvchi joylashtirish", formula: "\\bar{A}_n^k = n^k" },
      { id: "k8", name: "Takrorlanuvchi kombinatsiya", formula: "\\bar{C}_n^k = C_{n+k-1}^k" },
      { id: "k9", name: "Takrorlanuvchi o'rin alm.", formula: "P(n_1, n_2, ..., n_k) = \\frac{n!}{n_1! n_2! ... n_k!}" },
      { id: "k10", name: "Binom yig'indisi", formula: "\\sum_{k=0}^{n} C_n^k = 2^n" },
      { id: "k11", name: "Binom almashuvchi", formula: "\\sum_{k=0}^{n} (-1)^k C_n^k = 0" },
      { id: "k12", name: "Vandermonde ayniyati", formula: "C_{m+n}^r = \\sum_{k=0}^{r} C_m^k C_n^{r-k}" },
      { id: "k13", name: "Stirling soni (1-tur)", formula: "s(n,k): x^{\\underline{n}} = \\sum_{k=0}^{n} s(n,k) x^k" },
      { id: "k14", name: "Stirling soni (2-tur)", formula: "S(n,k) = \\frac{1}{k!}\\sum_{j=0}^{k}(-1)^j C_k^j (k-j)^n" },
      { id: "k15", name: "Derangement", formula: "D_n = n! \\sum_{k=0}^{n} \\frac{(-1)^k}{k!}" },
      { id: "k16", name: "Katalon soni", formula: "C_n = \\frac{1}{n+1}C_{2n}^n = \\frac{(2n)!}{(n+1)!n!}" },
    ]
  },
  {
    id: "sequences",
    title: "Ketma-ketliklar",
    icon: "List",
    formulas: [
      { id: "s1", name: "Arifmetik progressiya", formula: "a_n = a_1 + (n-1)d" },
      { id: "s2", name: "AP yig'indisi", formula: "S_n = \\frac{n(a_1 + a_n)}{2}" },
      { id: "s3", name: "Geometrik progressiya", formula: "b_n = b_1 \\cdot q^{n-1}" },
      { id: "s4", name: "GP yig'indisi", formula: "S_n = \\frac{b_1(q^n - 1)}{q - 1}" },
      { id: "s5", name: "Cheksiz GP", formula: "S = \\frac{b_1}{1-q}, \\quad |q| < 1" },
      { id: "s6", name: "Fibonachchi", formula: "F_n = F_{n-1} + F_{n-2}" },
      { id: "s7", name: "Fibonachchi formulasi", formula: "F_n = \\frac{\\phi^n - \\psi^n}{\\sqrt{5}}" },
      { id: "s8", name: "Oltin nisbat", formula: "\\phi = \\frac{1 + \\sqrt{5}}{2} \\approx 1.618" },
      { id: "s9", name: "Natural sonlar", formula: "\\sum_{k=1}^{n} k = \\frac{n(n+1)}{2}" },
      { id: "s10", name: "Kvadratlar yig'indisi", formula: "\\sum_{k=1}^{n} k^2 = \\frac{n(n+1)(2n+1)}{6}" },
      { id: "s11", name: "Kublar yig'indisi", formula: "\\sum_{k=1}^{n} k^3 = \\left[\\frac{n(n+1)}{2}\\right]^2" },
      { id: "s12", name: "Harmonik qator", formula: "H_n = \\sum_{k=1}^{n} \\frac{1}{k}" },
    ]
  },
  {
    id: "vectors",
    title: "Vektorlar",
    icon: "Move",
    formulas: [
      { id: "v1", name: "Vektor uzunligi", formula: "|\\vec{a}| = \\sqrt{a_x^2 + a_y^2 + a_z^2}" },
      { id: "v2", name: "Skalyar ko'paytma", formula: "\\vec{a} \\cdot \\vec{b} = |\\vec{a}||\\vec{b}|\\cos\\theta" },
      { id: "v3", name: "Skalyar koordinatada", formula: "\\vec{a} \\cdot \\vec{b} = a_xb_x + a_yb_y + a_zb_z" },
      { id: "v4", name: "Vektor ko'paytma", formula: "|\\vec{a} \\times \\vec{b}| = |\\vec{a}||\\vec{b}|\\sin\\theta" },
      { id: "v5", name: "Vektor ko'paytma det", formula: "\\vec{a} \\times \\vec{b} = \\begin{vmatrix} \\vec{i} & \\vec{j} & \\vec{k} \\\\ a_x & a_y & a_z \\\\ b_x & b_y & b_z \\end{vmatrix}" },
      { id: "v6", name: "Aralash ko'paytma", formula: "(\\vec{a}, \\vec{b}, \\vec{c}) = \\vec{a} \\cdot (\\vec{b} \\times \\vec{c})" },
      { id: "v7", name: "Burchak", formula: "\\cos\\theta = \\frac{\\vec{a} \\cdot \\vec{b}}{|\\vec{a}||\\vec{b}|}" },
      { id: "v8", name: "Proeksiya", formula: "\\text{pr}_{\\vec{b}}\\vec{a} = \\frac{\\vec{a} \\cdot \\vec{b}}{|\\vec{b}|}" },
      { id: "v9", name: "Birlik vektor", formula: "\\hat{a} = \\frac{\\vec{a}}{|\\vec{a}|}" },
      { id: "v10", name: "Uchburchak yuzi", formula: "S = \\frac{1}{2}|\\vec{a} \\times \\vec{b}|" },
    ]
  },
  {
    id: "matrices",
    title: "Matritsalar",
    icon: "Table",
    formulas: [
      { id: "m1", name: "2x2 determinant", formula: "\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix} = ad - bc" },
      { id: "m2", name: "3x3 determinant", formula: "\\det(A) = a(ei-fh) - b(di-fg) + c(dh-eg)" },
      { id: "m3", name: "Teskari matritsa", formula: "A^{-1} = \\frac{1}{\\det(A)} \\text{adj}(A)" },
      { id: "m4", name: "2x2 teskari", formula: "A^{-1} = \\frac{1}{ad-bc}\\begin{pmatrix} d & -b \\\\ -c & a \\end{pmatrix}" },
      { id: "m5", name: "Matritsa ko'paytirish", formula: "(AB)_{ij} = \\sum_{k} a_{ik}b_{kj}" },
      { id: "m6", name: "Transponirlash", formula: "(A^T)_{ij} = A_{ji}" },
      { id: "m7", name: "Xususiy qiymat", formula: "\\det(A - \\lambda I) = 0" },
      { id: "m8", name: "Iz (trace)", formula: "\\text{tr}(A) = \\sum_{i} a_{ii}" },
      { id: "m9", name: "Kramer qoidasi", formula: "x_i = \\frac{\\det(A_i)}{\\det(A)}" },
      { id: "m10", name: "Rang-nullity", formula: "\\text{rank}(A) + \\text{nullity}(A) = n" },
    ]
  },
];
